[package]
name = "shufflr"
version = "0.1.0"
authors = ["HÃ©ctor Tortosa <hectortosa@icloud.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }